"""
Dataset Loader
===============
Reads EVCP datasets from Excel files generated by the dataset generator.

Expected Excel format:
  Sheet "config":            key-value pairs (m, x_min, x_max, y_min, y_max, ...)
  Sheet "pois":              columns [x, y, density]
  Sheet "existing_chargers": columns [x, y]
  Sheet "gas_stations":      columns [x, y]

Usage
-----
    from data_loader import load_dataset

    data = load_dataset("dataset_medium_city.xlsx")

    # Unpack
    pois      = data['pois']               # list of (x, y, density)
    chargers  = data['existing_chargers']   # list of (x, y)
    gas       = data['gas_stations']        # list of (x, y)
    m         = data['m']
    x_min     = data['x_min']
    ...
"""

import pandas as pd
from typing import Dict, Any


def load_dataset(filepath: str) -> Dict[str, Any]:
    """
    Load an EVCP dataset from an Excel file.

    Parameters
    ----------
    filepath : str
        Path to the .xlsx file.

    Returns
    -------
    dict with keys:
        'dataset_name'       : str
        'description'        : str
        'm'                  : int — number of new chargers to place
        'x_min', 'x_max'    : float — geographic bounds
        'y_min', 'y_max'    : float
        'pois'               : list of (x, y, density) tuples
        'existing_chargers'  : list of (x, y) tuples
        'gas_stations'       : list of (x, y) tuples
    """
    # Read config sheet
    df_config = pd.read_excel(filepath, sheet_name="config", header=None,
                               names=["key", "value"])
    config = {}
    for _, row in df_config.iterrows():
        k = str(row["key"]).strip()
        v = row["value"]
        # Try numeric conversion
        if k in ('m', 'n_pois', 'n_chargers', 'n_gas'):
            config[k] = int(v)
        elif k in ('x_min', 'x_max', 'y_min', 'y_max'):
            config[k] = float(v)
        else:
            config[k] = v

    # Read POIs
    df_pois = pd.read_excel(filepath, sheet_name="pois")
    pois = [
        (float(row['x']), float(row['y']), float(row['density']))
        for _, row in df_pois.iterrows()
    ]

    # Read existing chargers
    df_ch = pd.read_excel(filepath, sheet_name="existing_chargers")
    chargers = [
        (float(row['x']), float(row['y']))
        for _, row in df_ch.iterrows()
    ]

    # Read gas stations
    df_gs = pd.read_excel(filepath, sheet_name="gas_stations")
    gas = [
        (float(row['x']), float(row['y']))
        for _, row in df_gs.iterrows()
    ]

    return {
        'dataset_name':      config.get('dataset_name', ''),
        'description':       config.get('description', ''),
        'm':                 config['m'],
        'x_min':             config['x_min'],
        'x_max':             config['x_max'],
        'y_min':             config['y_min'],
        'y_max':             config['y_max'],
        'pois':              pois,
        'existing_chargers': chargers,
        'gas_stations':      gas,
    }


def print_dataset_summary(data: Dict[str, Any]) -> None:
    """Pretty-print a loaded dataset."""
    print(f"Dataset: {data['dataset_name']}")
    print(f"  {data['description']}")
    print(f"  Area: [{data['x_min']}, {data['x_max']}] × [{data['y_min']}, {data['y_max']}]")
    print(f"  POIs: {len(data['pois'])}  |  "
          f"Chargers: {len(data['existing_chargers'])}  |  "
          f"Gas: {len(data['gas_stations'])}  |  m={data['m']}")
    if data['pois']:
        densities = [p[2] for p in data['pois']]
        print(f"  Density range: [{min(densities):.2f}, {max(densities):.2f}]  "
              f"mean={sum(densities)/len(densities):.2f}")


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        d = load_dataset(sys.argv[1])
        print_dataset_summary(d)
    else:
        print("Usage: python data_loader.py <dataset.xlsx>")
